import { Pool, types } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

// pg returns bigint (20) and numeric/decimal (1700) as strings by default.
// Parse them as JS numbers so aggregations (COUNT, SUM) work correctly.
types.setTypeParser(20, val => parseInt(val, 10));
types.setTypeParser(1700, val => parseFloat(val));
types.setTypeParser(1082, val => val); // DATE → keep as 'YYYY-MM-DD' string, not a UTC-shifted Date

let pool: Pool;

export async function initializeDb() {
    pool = new Pool({
        host: process.env.WH_DB_HOST || 'localhost',
        port: Number(process.env.WH_DB_PORT || 5432),
        database: process.env.WH_DB_NAME || 'dok_warehouse',
        user: process.env.WH_DB_USER || 'dokwarehouse',
        password: process.env.WH_DB_PASSWORD || '',
        max: 10,
        idleTimeoutMillis: 30000,
    });

    try {
        const client = await pool.connect();

        await client.query(`
            CREATE TABLE IF NOT EXISTS users (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username      VARCHAR(64) UNIQUE NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                name          VARCHAR(200) NOT NULL,
                role          VARCHAR(20) NOT NULL CHECK (role IN ('system_admin','warehouse_admin','finance_officer')),
                status        VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS companies (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(200) NOT NULL,
                code            VARCHAR(32) UNIQUE,
                contact_person  VARCHAR(200),
                phone           VARCHAR(64),
                email           VARCHAR(200),
                address         TEXT,
                status          VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS warehouses (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(200) NOT NULL,
                code            VARCHAR(32) UNIQUE,
                address         TEXT,
                status          VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        // Add warehouse_ids before migrating roles, so the staff->warehouse_admin
        // migration below can populate it in the same pass.
        await client.query(`
            ALTER TABLE users ADD COLUMN IF NOT EXISTS warehouse_ids INTEGER[] NOT NULL DEFAULT '{}'
        `);

        // Idempotent data migration from the old admin/staff role values to the
        // new 3-role model.
        //
        // NOTE: this block runs here (after the `warehouses` table is created)
        // rather than immediately after `users`/before `companies`, because it
        // queries `warehouses` below — placing it earlier would make that query
        // fail with "relation \"warehouses\" does not exist" on a genuinely
        // fresh database, crashing boot.
        //
        // NOTE: DROP CONSTRAINT runs BEFORE the migration UPDATEs below (not
        // after, as originally drafted). Verified against a live Postgres
        // instance seeded with real admin/staff rows: with the old
        // role IN ('admin','staff') constraint still in place, the very first
        // `UPDATE ... SET role = 'system_admin'` statement violates that old
        // constraint and crashes initializeDb() before the new constraint is
        // ever reached. Dropping the old constraint first (so no CHECK is
        // active while the intermediate/mixed role values exist), migrating
        // the data, and only then adding the new tightened constraint is the
        // order that is actually safe on an existing database.
        await client.query(`
            ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check
        `);
        await client.query(`
            UPDATE users SET role = 'system_admin' WHERE role = 'admin'
        `);
        const firstWarehouse = await client.query(`SELECT id FROM warehouses ORDER BY id LIMIT 1`);
        const defaultWarehouseIds = firstWarehouse.rows.length > 0 ? [firstWarehouse.rows[0].id] : [];
        await client.query(
            `UPDATE users SET role = 'warehouse_admin', warehouse_ids = $1 WHERE role = 'staff'`,
            [defaultWarehouseIds]
        );

        await client.query(`
            ALTER TABLE users ADD CONSTRAINT users_role_check
                CHECK (role IN ('system_admin', 'warehouse_admin', 'finance_officer'))
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS user_permission_overrides (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                permission_key  VARCHAR(50) NOT NULL CHECK (permission_key IN (
                    'manage_companies', 'manage_warehouses', 'manage_box_events',
                    'view_invoices', 'manage_invoices', 'manage_users', 'manage_expenses'
                )),
                granted         BOOLEAN NOT NULL,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (user_id, permission_key)
            )
        `);

        // Widen the permission_key CHECK to include manage_expenses. Safe to
        // run in any order relative to existing rows — this only ADDS an
        // allowed value, it never removes one, so no pre-existing row can
        // violate it (unlike the users.role migration above, which had to
        // migrate data before tightening).
        await client.query(`
            ALTER TABLE user_permission_overrides DROP CONSTRAINT IF EXISTS user_permission_overrides_permission_key_check
        `);
        await client.query(`
            ALTER TABLE user_permission_overrides ADD CONSTRAINT user_permission_overrides_permission_key_check
                CHECK (permission_key IN (
                    'manage_companies', 'manage_warehouses', 'manage_box_events',
                    'view_invoices', 'manage_invoices', 'manage_users', 'manage_expenses'
                ))
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS departments (
                id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id                INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
                warehouse_id              INTEGER NOT NULL REFERENCES warehouses(id),
                name                      VARCHAR(200) NOT NULL,
                code                      VARCHAR(32),
                status                    VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                current_box_count         INTEGER NOT NULL DEFAULT 0 CHECK (current_box_count >= 0),
                price_per_archived_box    NUMERIC(12,2) NOT NULL DEFAULT 0,
                price_per_retrieved_box   NUMERIC(12,2) NOT NULL DEFAULT 0,
                price_per_empty_carton    NUMERIC(12,2) NOT NULL DEFAULT 0,
                created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (company_id, name)
            )
        `);

        await client.query(`
            ALTER TABLE departments ADD COLUMN IF NOT EXISTS price_per_archived_box NUMERIC(12,2) NOT NULL DEFAULT 0
        `);
        await client.query(`
            ALTER TABLE departments ADD COLUMN IF NOT EXISTS price_per_retrieved_box NUMERIC(12,2) NOT NULL DEFAULT 0
        `);
        await client.query(`
            ALTER TABLE departments ADD COLUMN IF NOT EXISTS price_per_empty_carton NUMERIC(12,2) NOT NULL DEFAULT 0
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS box_events (
                id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                department_id  INTEGER NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
                event_type     VARCHAR(30) NOT NULL CHECK (event_type IN ('archived','retrieved','empty_carton_issued')),
                quantity       INTEGER NOT NULL CHECK (quantity > 0),
                event_date     DATE NOT NULL,
                reference_no   VARCHAR(64),
                remarks        TEXT,
                created_by     INTEGER REFERENCES users(id),
                created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_box_events_department ON box_events(department_id)
        `);
        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_box_events_date ON box_events(event_date)
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS warehouse_expenses (
                id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                warehouse_id       INTEGER NOT NULL REFERENCES warehouses(id),
                expense_date       DATE NOT NULL,
                transport_amount   NUMERIC(12,2) NOT NULL DEFAULT 0,
                fuel_amount        NUMERIC(12,2) NOT NULL DEFAULT 0,
                labour_amount      NUMERIC(12,2) NOT NULL DEFAULT 0,
                meals_amount       NUMERIC(12,2) NOT NULL DEFAULT 0,
                other_amount       NUMERIC(12,2) NOT NULL DEFAULT 0,
                remarks            TEXT,
                created_by         INTEGER REFERENCES users(id),
                created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (warehouse_id, expense_date)
            )
        `);

        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_warehouse_expenses_date ON warehouse_expenses(expense_date)
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS invoices (
                id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                department_id             INTEGER NOT NULL REFERENCES departments(id),
                company_id                INTEGER NOT NULL REFERENCES companies(id),
                department_name           VARCHAR(200) NOT NULL,
                company_name              VARCHAR(200) NOT NULL,
                period_from               DATE NOT NULL,
                period_to                 DATE NOT NULL,
                archived_count            INTEGER NOT NULL DEFAULT 0,
                retrieved_count           INTEGER NOT NULL DEFAULT 0,
                empty_carton_count        INTEGER NOT NULL DEFAULT 0,
                price_per_archived_box    NUMERIC(12,2) NOT NULL,
                price_per_retrieved_box   NUMERIC(12,2) NOT NULL,
                price_per_empty_carton    NUMERIC(12,2) NOT NULL,
                subtotal                  NUMERIC(14,2) NOT NULL,
                sscl_amount               NUMERIC(14,2) NOT NULL,
                vat_amount                NUMERIC(14,2) NOT NULL,
                total_amount              NUMERIC(14,2) NOT NULL,
                created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
                created_by                INTEGER REFERENCES users(id),
                UNIQUE (department_id, period_from, period_to)
            )
        `);

        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_invoices_department ON invoices(department_id)
        `);

        client.release();
        console.log('Warehouse DB pool created');
    } catch (err) {
        console.error('Error creating warehouse DB pool', err);
        process.exit(1);
    }
}

export async function closeDb() {
    if (pool) {
        await pool.end();
        console.log('Warehouse DB pool closed');
    }
}

export function getPool(): Pool {
    return pool;
}
