import { Pool, types } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

// pg returns bigint (20) and numeric/decimal (1700) as strings by default.
// Parse them as JS numbers so aggregations (COUNT, SUM) work correctly.
types.setTypeParser(20, val => parseInt(val, 10));
types.setTypeParser(1700, val => parseFloat(val));
types.setTypeParser(1082, val => val); // DATE → keep as 'YYYY-MM-DD' string, not a UTC-shifted Date

let pool: Pool;

export async function initializeDb() {
    pool = new Pool({
        host: process.env.WH_DB_HOST || 'localhost',
        port: Number(process.env.WH_DB_PORT || 5432),
        database: process.env.WH_DB_NAME || 'dok_warehouse',
        user: process.env.WH_DB_USER || 'dokwarehouse',
        password: process.env.WH_DB_PASSWORD || '',
        max: 10,
        idleTimeoutMillis: 30000,
    });

    try {
        const client = await pool.connect();

        await client.query(`
            CREATE TABLE IF NOT EXISTS users (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username      VARCHAR(64) UNIQUE NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                name          VARCHAR(200) NOT NULL,
                role          VARCHAR(20) NOT NULL CHECK (role IN ('admin','staff')),
                status        VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS companies (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(200) NOT NULL,
                code            VARCHAR(32) UNIQUE,
                contact_person  VARCHAR(200),
                phone           VARCHAR(64),
                email           VARCHAR(200),
                address         TEXT,
                status          VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS warehouses (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(200) NOT NULL,
                code            VARCHAR(32) UNIQUE,
                address         TEXT,
                status          VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS departments (
                id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id         INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
                warehouse_id       INTEGER NOT NULL REFERENCES warehouses(id),
                name               VARCHAR(200) NOT NULL,
                code               VARCHAR(32),
                status             VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
                current_box_count  INTEGER NOT NULL DEFAULT 0 CHECK (current_box_count >= 0),
                created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (company_id, name)
            )
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS box_events (
                id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                department_id  INTEGER NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
                event_type     VARCHAR(30) NOT NULL CHECK (event_type IN ('archived','retrieved','empty_carton_issued')),
                quantity       INTEGER NOT NULL CHECK (quantity > 0),
                event_date     DATE NOT NULL,
                reference_no   VARCHAR(64),
                remarks        TEXT,
                created_by     INTEGER REFERENCES users(id),
                created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        `);

        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_box_events_department ON box_events(department_id)
        `);
        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_box_events_date ON box_events(event_date)
        `);

        client.release();
        console.log('Warehouse DB pool created');
    } catch (err) {
        console.error('Error creating warehouse DB pool', err);
        process.exit(1);
    }
}

export async function closeDb() {
    if (pool) {
        await pool.end();
        console.log('Warehouse DB pool closed');
    }
}

export function getPool(): Pool {
    return pool;
}
